### ISSUE TITLE
CS_REST_Subscribers::unsubscribe() unsubscribes from all lists

### ISSUE THREAD

**Issue by vedkaps** [campaignmonitor/createsend-php#78]
```
$cs = new CS_REST_Subscribers('list_id', $auth);
$cs = $cs->unsubscribe('my@email.com');
```

This actually unsubscribes email from all lists instead only the given list ID. As a solution you have to go loop through all lists and resubscribe the email.

**Comment by taledo** [comment]
Hi @vedkaps,
The default behaviour of a list is to "Remove them from all X lists (recommended)". So if you have 10 lists, with the same subscriber 10 times, even if you specify a list ID in the API, it will honour this setting first. You can however change this _per_ list.
On the lists page in the UI, underneath "Segments" URL on the right hand side, you will see a link **"Unsubscribe Settings"**.
If you change the setting to "Only remove them from this list", and try the code above, you will see that this will now only remove them from the intended list.
This is by design.
Cheers
Pete
